[package]
name = "oxicodent"
version = "0.5.2"
edition = "2024"

[dependencies]
serde = { version = "0.5.2"] }
serde_json = "1.0.149"
serde_yaml = "0.9.19"
reqwest = { version = "0.5.2"] }
ratatui = "0.30.0"
crossterm = "0.29.0"
chrono = "0.4.43"
diffy = "0.4.2"