[package]
name = "oxicodent"
version = "0.1.0"
edition = "2024"

[dependencies]
serde = { version = "1.0.228", features = ["derive"] }
home = "0.5.12"
serde_json = "1.0.149"
rustyline = "17.0.2"
colored = "3.1.1"
reqwest = { version = "0.13.2", features = ["blocking", "json"] }
